spring:
  application:
    name: recipes-api
  datasource:
    url: jdbc:postgresql://localhost:5432/recipes
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  sql:
    init:
      mode: never

springdoc:
  swagger-ui:
    path: /swagger-ui.html