spring:
  application:
    name: recipes-api
  datasource:
    url: jdbc:h2:mem:recipes
    username: sa
    password: password
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false
  sql:
    init:
      mode: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html